### ISSUE TITLE
Missing license information at nuget.org

### ISSUE THREAD

**Issue by MH321Productions** [Megasware128/serilog-enrichers-demystifier#2]
The project license is not set inside the nuget package (or specifically, the [product page](https://www.nuget.org/packages/Serilog.Enrichers.Demystifier)).

Therefore, the tool [nuget-license](https://github.com/sensslen/nuget-license) fails when trying to check the license ("No license information found").

**Comment by Megasware128** [comment]
Should be fixed with v1.0.3
